### ISSUE TITLE
Line endings problems

### ISSUE THREAD

**Issue by japro** [vbmacher/emuStudio#98] opened 2016-01-21 19:50 UTC
I have posted a pull request yesterday, and you told  me to undo changes from commit. The problem seems to be line endings, because  when I clone your project, even if I don't change anything,and check git status, it shows these file as modified:

On branch branch-0_39
Your branch is up-to-date with 'origin/branch-0_39'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   plugins/compilers/as-8080/examples/include/getchar.inc
	modified:   plugins/compilers/as-8080/examples/include/getline.inc
	modified:   plugins/compilers/as-8080/examples/include/newline.inc
	modified:   plugins/compilers/as-8080/examples/include/putchar.inc
	modified:   plugins/compilers/as-8080/examples/include/putstr.inc
	modified:   plugins/cpu/brainduck-cpu/src/main/edigen/cpu.eds
	modified:   plugins/cpu/brainduck-cpu/src/main/resources/net/sf/emustudio/braincpu/version.properties

**Comment by japro** [comment] 2016-01-21 19:51
I can't solve this, these files are shown as modified even if I check them out...

**Comment by vbmacher** [comment] 2016-01-22 08:16
The problem is in git settings. See https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration section `core.autocrlf`.

For Windows, recommended setting is:

```
git config --global core.autocrlf=true
```

Which should handle the line endings correctly (CRLF when you're working with files, LF on commit). 

However, I am using `.gitattributes` file where it is explicitly said which file extension is having which line ending. Look at file https://github.com/vbmacher/emuStudio/blob/branch-0_39/.gitattributes 

It is enough to add extensions `*.inc`, `*.eds`, and `*.properties` to that file with LF as line ending.

**Comment by vbmacher** [comment] 2016-01-26 09:36
This should be fixed, closing.

**Closed** 2016-01-26 09:35 UTC
